apiVersion: apps/v1
kind: Deployment
metadata:
  name: testbench
  labels:
    app: testbench
spec:
  selector:
    matchLabels:
      app: testbench
  replicas: 1
  template:
    metadata:
      labels:
        app: testbench
    spec:
      containers:
      - name: testbench
        image: gcr.io/zeebe-io/zeebe-cluster-testbench:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        env:
          - name: ZCTB_AUTHENTICATION_SERVER_URL
            value: "https://login.cloud.ultrawombat.com/oauth/token"
          - name: ZCTB_CLIENT_ID
            value: "9VahED9_bzhBLGhHt3kVRDzCzYpmLhe_"
          - name: ZCTB_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: testbench-secrets
                key: clientSecret
          - name: ZCTB_CONTACT_POINT
            valueFrom:
              secretKeyRef:
                name: testbench-secrets
                key: contactPoint
          - name: ZCTB_CLOUD_API_URL
            value: "https://console.cloud.ultrawombat.com/customer-api/"
          - name: ZCTB_CLOUD_AUDIENCE
            value: "api.cloud.ultrawombat.com"
          - name: ZCTB_CLOUD_AUTHENTICATION_SERVER_URL
            value: "https://login.cloud.ultrawombat.com/oauth/token"
          - name: ZCTB_CLOUD_CLIENT_ID
            value: "9wGSXQvbUNn0fzi~"
          - name: ZCTB_CLOUD_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: testbench-secrets
                key: cloudClientSecret
          - name: ZCTB_REPORT_SHEET_ID
            value: "1l3ofIIHKHWTjRs1IpZYl1ULMfqkyGpL7JRarkR0of94"
          - name: ZCTB_SLACK_TOKEN
            valueFrom:
              secretKeyRef:
                name: testbench-secrets
                key: slackToken            
        resources:
          limits:
            cpu: 4
            memory: 256Mi
          requests:
            cpu: 2
            memory: 1002Mi
